export { default as Home } from "./Home";
// export { default as Products } from "../components/Products.jsx";
// export { default as Product } from "../components/Product.jsx";
export { default as AboutPage } from "./AboutPage";
export { default as ContactPage } from "./ContactPage";
export { default as Cart } from "../components/Cart.jsx";
export { default as Login } from "../components/Login.jsx";
export { default as Register } from "../components/Register.jsx";
export { default as Checkout } from "./CheckoutPage.jsx";
export { default as PageNotFound } from "./PageNotFound.jsx";
export { default as ProfileRoutes } from "./ProfilePage.jsx";
// export { default as ProfilePage } from "./ProfilePage.jsx";
export { default as OrdersListPage } from "./OrdersListPage.jsx";
export { default as ProductPage } from "./ProductPage.jsx";
export { default as UpdPageProfile } from "./UpdPageProfile.jsx";
// export { default as WishListPage } from "./WishListPage.jsx";
